### ISSUE TITLE
Annotate `Interval` with `@Embeddable`

### ISSUE THREAD

**Issue by odrotbohm** [st-tu-dresden/salespoint#370]
Just to make more obvious that the type can be persisted out of the box.

**Comment by odrotbohm** [comment]
Steps to complete:

- [ ] Annotate `Interval` with `@Embeddable`.
- [ ] Add property of type `Interval` to `DummyEntity`
- [ ] Create test case class `DummyEntityRepositoryIntegrationTests`, annotated with `@SpringBootTest`
- [ ] Dependency inject `DummyRepository`, create an instance of `DummyEntity`, persist that and read it back again to verify that the `Interval` property can be written and read.

**Comment by odrotbohm** [comment]
It looks like fundamental support for this has already been implemented with #152.
